services:
  mysql:
    image: mysql:8.0
    container_name: contabilidad_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contabilidad
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - contabilidad_net

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: contabilidad_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./tests/backend:/var/www/tests/backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - contabilidad_net

  frontend:
    image: node:20
    container_name: contabilidad_frontend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules  # Evita conflictos con node_modules del host
    ports:
      - "5173:5173"
    networks:
      - contabilidad_net
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped

networks:
  contabilidad_net:

volumes:
  mysql_data:

